In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import requests
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [93]:
df = pd.read_csv('company_name.csv')
df.head()

                      company_name                                      link
0   Professional Diversity Network  https://www.linkedin.com/company/2043953
1          1-800-FLOWERS.COM, INC.     https://www.linkedin.com/company/8474
2                      1800PetMeds   https://www.linkedin.com/company/222996
3            1st Constitution Bank   https://www.linkedin.com/company/477479
4  1st Security Bank of Washington  https://www.linkedin.com/company/1912061

In [94]:
df_symbol = pd.read_csv('data/yahoo_stocklist.csv') #'data/tickers.csv'
display(df_symbol.head(10))
print(len(df_symbol))

,YAHOO TICKER,COMPANY NAME,INDUSTRY,COUNTRY TRADED,EXCHANGE
0,ADARSHPL.BO,Adarsh Plant Protect Ltd,Agricultural Chemicals,India,Bombay Stock Exchange
1,AFPO.L,African Potash Ltd,Agricultural Chemicals,United Kingdom,London Stock Exchange
2,AGU.DE,Agrium Inc,Agricultural Chemicals,Germany,XETRA Stock Exchange
3,AGU.TO,Agrium Inc,Agricultural Chemicals,Canada,Toronto Stock Exchange
4,AGU,Agrium Inc.,Agricultural Chemicals,United States of America,NaN
5,AIMCO.BO,Aimco Pesticides Ltd,Agricultural Chemicals,India,Bombay Stock Exchange
6,AVD,American Vanguard Corp.,Agricultural Chemicals,United States of America,NaN
7,ARIES.BO,Aries Agro Ltd,Agricultural Chemicals,India,Bombay Stock Exchange
8,ARIES.NS,Aries Agro Ltd,Agricultural Chemicals,India,National Stock Exchange of India
9,BASANTGL.BO,Basant Agro-Tech India Ltd,Agricultural Chemicals,India,Bombay Stock Exchange

27144

In [95]:
iwant = (df_symbol['COMPANY NAME'].notnull())
iwant &= (df_symbol['COUNTRY TRADED']=='United States of America')
df_symbol_us = df_symbol[iwant]
print(len(df_symbol_us))

7247

In [96]:
def trans_name(name):
    return name.lower().split(',')[0].split(' inc.')[0].split('.com')[0]

def check_name(name1, name2):
    len1, len2 = len(name1), len(name2)
    if len1 == len2:
        return name1 == name2
    elif len1 < len2:
        return (name1 == name2[:len1]) & (not name2[len1].isalnum()) # ensure the word stoped at the same position
    else:
        return False#(name1[:len2] == name2) & (not name1[len2].isalnum())

def find_symbol(name):
    symbols = []
    name1 = trans_name(name)
    if len(symbols) == 0:
        iwant = df_symbol_us['COMPANY NAME'].apply(lambda x: name1 == trans_name(x))
        symbols = df_symbol_us['YAHOO TICKER'][iwant].values
    if len(symbols) == 0:
        iwant = df_symbol_us['YAHOO TICKER'].apply(lambda x: name1 == x.lower())
        symbols = df_symbol_us['YAHOO TICKER'][iwant].values
    if len(symbols) == 0:
        iwant = df_symbol_us['COMPANY NAME'].apply(lambda x: check_name(name1, trans_name(x)) )
        symbols = df_symbol_us['YAHOO TICKER'][iwant].values
    
    symbols = list(set(symbols))
    return symbols

In [98]:
df['symbol'] = df['company_name'].apply(lambda name: find_symbol(name))

In [99]:
len(df[df['symbol'].apply(lambda x: len(x)>0)])

2375

In [100]:
df[df['symbol'].apply(lambda x: len(x)>1)]

,company_name,link,symbol
268,Altisource,https://www.linkedin.com/company/462395,"[AAMC, RESI, ASPS]"
311,American National,https://www.linkedin.com/company/16263,"[ANAT, AMNB]"
346,Anheuser-Busch InBev,https://www.linkedin.com/company/255188,"[ABI.BR, BUD]"
476,Atlanticus,https://www.linkedin.com/company/6134,"[ATLCF, ATLC, ATLCY]"
1084,China Mobile,https://www.linkedin.com/company/18257,"[CHL, CMGE]"
1139,ClearSign Combustion Corp,https://www.linkedin.com/company/1405011,"[CLIR, CLIRF]"
1472,Dominion,https://www.linkedin.com/company/5666,"[DM, D, DDC, DOM]"
1559,Eaton,https://www.linkedin.com/company/2599,"[EV, ETN]"
1605,Emerson,https://www.linkedin.com/company/2753,"[MSN, EMR]"
2023,Google,https://www.linkedin.com/company/1441,"[GOOG, GOOGL]"
2034,Gray Television,https://www.linkedin.com/company/82385,"[GTN-A, GTN]"
2084,HEICO,https://www.linkedin.com/company/29618,"[HEI-A, HEI]"
2244,Hudson,https://www.linkedin.com/company/2343,"[HPP, HSON, HDSN, HVB, HCBK]"
2350,Independent Bank,https://www.linkedin.com/company/28246,"[IBCP, IBTX, INDB]"
2407,Intercept Pharmaceuticals,https://www.linkedin.com/company/1319068,"[ICPT, ICPTF]"
2478,Jacobs,https://www.linkedin.com/company/4025,"[JEC, JFGI]"
3610,Quantum,https://www.linkedin.com/company/157300,"[QTWW, QEGY, QTM, QSPW]"
3917,"Sears, Roebuck and Co.",https://www.linkedin.com/company/1942,"[SHLD, SHOS]"
3987,Signet,https://www.linkedin.com/company/13626,"[SIGN, SIG]"
4068,Sotherly Hotels Inc.,https://www.linkedin.com/company/1234319,"[SOHOF, SOHO]"
4091,Spectra Energy,https://www.linkedin.com/company/4064,"[SEP, SE]"
4260,TOTAL,https://www.linkedin.com/company/1818,"[TSS, TOT]"
4284,Targa Resources,https://www.linkedin.com/company/36649,"[TRGP, NGLS]"
4305,Teekay,https://www.linkedin.com/company/10144,"[TNK, TOO, TGP, TK]"
4388,"The First, A National Banking Association",https://www.linkedin.com/company/1815046,"[FMD, FNLC, FLIC]"
4477,Total,https://www.linkedin.com/company/1818,"[TSS, TOT]"
4500,Transocean,https://www.linkedin.com/company/8210,"[RIGP, RIG]"
4614,Unilever,https://www.linkedin.com/company/1248,"[UL, UN]"
4844,Westlake Chemical,https://www.linkedin.com/company/47905,"[WLK, WLKP]"
4864,Williams,https://www.linkedin.com/company/50711,"[WPZ, WSM, WMB]"
4866,Willis,https://www.linkedin.com/company/3994,"[WLFC, WSH]"
4871,Windstream,https://www.linkedin.com/company/12709,"[WIN, WSTI]"

In [101]:
mapping = {'Altisource': ['ASPS'],
            'American National': ['ANAT'],
            'Anheuser-Busch InBev': ['BUD'],
            'Atlanticus': ['ATLC'],
            'China Mobile': ['CHL'],
            'ClearSign Combustion Corp': ['CLIR'],
            'Dominion': ['D'],
            'Eaton': ['ETN'],
            'Emerson': ['EMR'],
            'Express Scripts': [],
            'Google': ['GOOG', 'GOOGL'],
            'Gray Television': ['GTN'],
            'HEICO': ['HEI'],
            'Hudson': ['HSON'],
            'Independent Bank': ['IBCP'],
            'Intercept Pharmaceuticals': ['ICPT'],
            'Jacobs': ['JEC'],
            'Quantum': ['QMCO'],
            'Rayonier Advanced Materials': ['RYAM'],
            'Sears, Roebuck and Co.': ['SHLDQ'],
            'Signet': ['SIG'],
            'Sotherly Hotels Inc.': ['SOHO'],
            'Spectra Energy': [],
            'TOTAL': ['TOT'],
            'Targa Resources': ['TRGP'],
            'Teekay': ['TK'],
            'The First, A National Banking Association': [],
            'Theravance Biopharma US, Inc.': ['TBPH'],
            'Total': ['TOT'],
            'Transocean': ['TRGP'],
            'Unilever': ['UL', 'UN'],
            'Westlake Chemical': ['WLK'],
            'Williams': ['WMB'],
            'Willis': ['WLTW'],
            'Windstream': []
          }
for name in mapping:
    i = df[df['company_name'] == name].index[0]
    df.loc[i,'symbol'] = mapping[name]

In [102]:
df[df['symbol'].apply(lambda x: len(x)>1)]

     company_name                                   link         symbol
2023       Google  https://www.linkedin.com/company/1441  [GOOG, GOOGL]
4614     Unilever  https://www.linkedin.com/company/1248       [UL, UN]

In [103]:
symbols = []
names = []
for i in range(len(df)):
    symbol_i = df.loc[i,'symbol']
    name = df.loc[i,'company_name']
    for symbol in symbol_i:
        names.append(name)
        symbols.append(symbol)

In [104]:
df_out = pd.DataFrame(names)
df_out.columns = ['company_name']
df_out['symbol'] = symbols
df_out.to_csv('symbols.csv',index=False)

In [105]:
import pandas as pd
import numpy as np
from pandas_datareader import data, wb
import datetime

df_out = pd.read_csv('symbols.csv')
symbols = df_out['symbol'].values
names = df_out['company_name'].values

In [36]:
for symbol in symbols:
    try:
        df_i = data.DataReader(symbol, 'yahoo', start='2015-1-1', end = '2018-12-31')
        df_i.to_csv('data/stocks/'+symbol+'.csv')
    except:
        print('not avaliable for '+ symbol)

not avaliable for SHLM
not avaliable for ANN
not avaliable for AOL
not avaliable for AVHI
not avaliable for ABAX
not avaliable for ACXM
not avaliable for AET
not avaliable for AFFX
not avaliable for AOI
not avaliable for AFSI
not avaliable for AMBTQ
not avaliable for AMDA
not avaliable for ARII
not avaliable for ANN
not avaliable for APRI
not avaliable for ARDM
not avaliable for ARUN
not avaliable for AXLL
not avaliable for BTUI
not avaliable for BWINB
not avaliable for ABX
not avaliable for BIOD
not avaliable for BBOX
not avaliable for BWP
not avaliable for BRDR
not avaliable for TEU
not avaliable for BRCM
not avaliable for CA
not avaliable for CEB
not avaliable for CEB
not avaliable for CGG
not avaliable for CGI
not avaliable for CSC
not avaliable for CSG
not avaliable for PRSS
not avaliable for ABCD
not avaliable for CAM
not avaliable for CFN
not avaliable for CSCD
not avaliable for CPXX
not avaliable for CPHD
not avaliable for HOTR
not avaliable for CBAK
not avaliable for CNET
not avaliable for COBZ
not avaliable for COBZ
not avaliable for CTCT
not avaliable for CVG
not avaliable for CORI
not avaliable for CVD
not avaliable for COVS
not avaliable for CYNI
not avaliable for DCT
not avaliable for DDR
not avaliable for DAEG
not avaliable for DWCH
not avaliable for DWRE
not avaliable for DWRE
not avaliable for DEPO
not avaliable for DNB
not avaliable for DYAX
not avaliable for EXL
not avaliable for ELNK
not avaliable for ELON
not avaliable for ECR
not avaliable for EGLT
not avaliable for ESYS
not avaliable for ESIO
not avaliable for EEP
not avaliable for EEP
not avaliable for ECYT
not avaliable for EGN
not avaliable for ENI
not avaliable for EVHC
not avaliable for ENVI
not avaliable for EQY
not avaliable for ESL
not avaliable for EVDY
not avaliable for FCS
not avaliable for FDO
not avaliable for FBR
not avaliable for FNGN
not avaliable for FCE-A
not avaliable for FMI
not avaliable for GGP
not avaliable for GGP
not avaliable for GFA
not avaliable for GZT
not avaliable for GY
not avaliable for GGP
not avaliable for GPT
not avaliable for GB
not avaliable for HTS
not avaliable for HPY
not avaliable for AWAY
not avaliable for AWAY
not avaliable for AWAY
not avaliable for HSP
not avaliable for IACI
not avaliable for IHS
not avaliable for IHS
not avaliable for IMS
not avaliable for ITG
not avaliable for IMPV
not avaliable for IMMY
not avaliable for INTX
not avaliable for ISIS
not avaliable for JMBA
not avaliable for KTWO
not avaliable for KCG
not avaliable for KMG
not avaliable for KERX
not avaliable for KING
not avaliable for KONE
not avaliable for LOXO
not avaliable for LPTN
not avaliable for LHO
not avaliable for TAX
not avaliable for TAX
not avaliable for LOCK
not avaliable for LNKD
not avaliable for LYV
not avaliable for LYV
not avaliable for LYG
not avaliable for LMT
not avaliable for LOGM
not avaliable for LOW
not avaliable for LOXO
not avaliable for LUB
not avaliable for LL
not avaliable for LMNX
not avaliable for LUNA
not avaliable for LXFT
not avaliable for LDL
not avaliable for LYB
not avaliable for MTB
not avaliable for MHO
not avaliable for MAA
not avaliable for MAMS
not avaliable for MMS
not avaliable for MBFI
not avaliable for MBI
not avaliable for MDU
not avaliable for MD
not avaliable for MD
not avaliable for MEIP
not avaliable for MFA
not avaliable for MGIC
not avaliable for MGM
not avaliable for MGPI
not avaliable for MG
not avaliable for MKSI
not avaliable for MRC
not avaliable for MSCI
not avaliable for MTBC
not avaliable for MTSC
not avaliable for MYRG
not avaliable for MCBC
not avaliable for MFNC
not avaliable for MGNX
not avaliable for MCUR
not avaliable for M
not avaliable for MGLN
not avaliable for MMP
not avaliable for MPET
not avaliable for MGA
not avaliable for MX
not avaliable for MNGA
not avaliable for COOL
not avaliable for MMYT
not avaliable for MANT
not avaliable for MANU
not avaliable for MANH
not avaliable for MNTX
not avaliable for MTEX
not avaliable for MN
not avaliable for MAN
not avaliable for MFC
not avaliable for MRO
not avaliable for MPC
not avaliable for MCHX
not avaliable for MMI
not avaliable for MRIN
not avaliable for HZO
not avaliable for MRNS
not avaliable for MWE
not avaliable for MKL
not avaliable for MKTX
not avaliable for MRKT
not avaliable for MRLN
not avaliable for MAR
not avaliable for MBII
not avaliable for MMC
not avaliable for MRTN
not avaliable for MLM
not avaliable for MTZ
not avaliable for MTZ
not avaliable for MTZ
not avaliable for MAS
not avaliable for MASI
not avaliable for DOOR
not avaliable for MA
not avaliable for MA
not avaliable for MTDR
not avaliable for MTLS
not avaliable for MTRX
not avaliable for MTRX
not avaliable for MATX
not avaliable for MAT
not avaliable for MATR
not avaliable for MATW
not avaliable for MXL
not avaliable for MXIM
not avaliable for MXIM
not avaliable for MXWL
not avaliable for MKC
not avaliable for MDR
not avaliable for MCD
not avaliable for MGRC
not avaliable for MHFI
not avaliable for MCK
not avaliable for MTL
not avaliable for MDWD
not avaliable for MPW
not avaliable for MNOV
not avaliable for MDSO
not avaliable for MED
not avaliable for MDT
not avaliable for MEET
not avaliable for MLNX
not avaliable for MELI
not avaliable for MERC
not avaliable for MERC
not avaliable for MRK
not avaliable for MRCY
not avaliable for MDP
not avaliable for MRGE
not avaliable for VIVO
not avaliable for MMSI
not avaliable for MTH
not avaliable for MTOR
not avaliable for MACK
not avaliable for MLAB
not avaliable for MET
not avaliable for MTD
not avaliable for MDXG
not avaliable for MIXT
not avaliable for KORS
not avaliable for MSTR
not avaliable for MVIS
not avaliable for MCHP
not avaliable for MCHP
not avaliable for MU
not avaliable for MSFT
not avaliable for MCEP
not avaliable for MPO
not avaliable for MM
not avaliable for MLR
not avaliable for MTX
not avaliable for MRTX
not avaliable for MRTX
not avaliable for MSON
not avaliable for MIND
not avaliable for MITK
not avaliable for MITL
not avaliable for MOSY
not avaliable for MINI
not avaliable for MINI
not avaliable for MOBL
not avaliable for MODN
not avaliable for MOD
not avaliable for MC
not avaliable for MHK
not avaliable for MOH
not avaliable for TAP
not avaliable for MNTA
not avaliable for MPWR
not avaliable for TYPE
not avaliable for MNRO
not avaliable for MNRO
not avaliable for MCO
not avaliable for MS
not avaliable for MORN
not avaliable for MPAA
not avaliable for MSI
not avaliable for MOV
not avaliable for MLI
not avaliable for MWA
not avaliable for MUR
not avaliable for MUSA
not avaliable for MYE
not avaliable for MYL
not avaliable for MYGN
not avaliable for NSSC
not avaliable for NCS
not avaliable for NCR
not avaliable for NTGR
not avaliable for NTCT
not avaliable for NTWK
not avaliable for EGOV
not avaliable for NNBR
not avaliable for NOAH
not avaliable for NVAX
not avaliable for NRG
not avaliable for NSP
not avaliable for NVEE
not avaliable for NVDA
not avaliable for NVR
not avaliable for NXPI
not avaliable for NBR
not avaliable for NSTG
not avaliable for NANO
not avaliable for NSPH
not avaliable for NATH
not avaliable for NAUH
not avaliable for FIZZ
not avaliable for NCMI
not avaliable for NFG
not avaliable for NGG
not avaliable for NHI
not avaliable for NATI
not avaliable for NOV
not avaliable for NPK
not avaliable for NNN
not avaliable for NWLI
not avaliable for NSM
not avaliable for NTZ
not avaliable for NLS
not avaliable for NAVI
not avaliable for NCI
not avaliable for NP
not avaliable for NKTR
not avaliable for NNI
not avaliable for NEO
not avaliable for NPTN
not avaliable for NEON
not avaliable for NETE
not avaliable for NTAP
not avaliable for NTES
not avaliable for NFLX
not avaliable for NLST
not avaliable for CUR
not avaliable for NURO
not avaliable for NBIX
not avaliable for NVRO
not avaliable for NJR
not avaliable for NWY
not avaliable for NLNK
not avaliable for NEU
not avaliable for NFX
not avaliable for NEM
not avaliable for NR
not avaliable for NEE
not avaliable for NEE
not avaliable for NI
not avaliable for NICK
not avaliable for NLSN
not avaliable for NKE
not avaliable for NKE
not avaliable for NBL
not avaliable for NOK
not avaliable for NMR
not avaliable for NDLS
not avaliable for NCFT
not avaliable for NDSN
not avaliable for JWN
not avaliable for NSC
not avaliable for NSYS
not avaliable for NTRS
not avaliable for NFBK
not avaliable for NOC
not avaliable for NOC
not avaliable for NVMI
not avaliable for NVS
not avaliable for NVO
not avaliable for NUS
not avaliable for NS
not avaliable for NUVA
not avaliable for NUAN
not avaliable for NUE
not avaliable for NTRI
not avaliable for NXTM
not avaliable for OIIM
not avaliable for OCLR
not avaliable for OGE
not avaliable for OMN
not avaliable for ONNN
not avaliable for OKE
not avaliable for OPK
not avaliable for ORBC
not avaliable for OSIS
not avaliable for OTEL
not avaliable for OUT
not avaliable for OAS
not avaliable for OPTT

not avaliable for ORIG
not avaliable for OII
not avaliable for OZM
not avaliable for OCLS
not avaliable for OMEX
not avaliable for ODP
not avaliable for OHRP
not avaliable for OIS
not avaliable for ODFL
not avaliable for OLN
not avaliable for ZEUS
not avaliable for OHI
not avaliable for OFLX
not avaliable for OMER
not avaliable for OCR
not avaliable for OMCL
not avaliable for OPWR
not avaliable for OWW
not avaliable for ORBK
not avaliable for OVAS
not avaliable for P
not avaliable for P
not avaliable for PRKR
not avaliable for PTX
not avaliable for PERY
not avaliable for PZE
not avaliable for PCYC
not avaliable for PNK
not avaliable for PF
not avaliable for PZZI
not avaliable for PPS
not avaliable for POWR
not avaliable for PX
not avaliable for PX
not avaliable for PVLY
not avaliable for BIN
not avaliable for QSII
not avaliable for RGP
not avaliable for RLJE
not avaliable for RMGN
not avaliable for RSPP
not avaliable for RSYS
not avaliable for REIS
not avaliable for REMY
not avaliable for RPI
not avaliable for COL
not avaliable for ROVI
not avaliable for SMTP
not avaliable for SVU
not avaliable for SN
not avaliable for SHLD
not avaliable for SNMX
not avaliable for SWHC
not avaliable for SODA
not avaliable for SCTY
not avaliable for SXE
not avaliable for SSS
not avaliable for SQBK
not avaliable for SXL
not avaliable for SGYP
not avaliable for SGYP
not avaliable for SYNT
not avaliable for TSRO
not avaliable for TSYS
not avaliable for TPIV
not avaliable for TSRA
not avaliable for TXTR
not avaliable for DOW
not avaliable for THRX
not avaliable for TRMR
not avaliable for TCAP
not avaliable for TRLA
not avaliable for TUBE
not avaliable for UBIC
not avaliable for VVC
not avaliable for PAY
not avaliable for VSAR
not avaliable for VSTA
not avaliable for WSCI
not avaliable for WWWW
not avaliable for WFM
not avaliable for XOXO
not avaliable for XCRA
not avaliable for XRM
not avaliable for XPLR
not avaliable for YHOO
not avaliable for YHOO
not avaliable for YHOO
not avaliable for ZSPH
not avaliable for ATHN
not avaliable for IPAS
not avaliable for SAAS
not avaliable for CALL
not avaliable for XGTI

In [106]:
df_drop = pd.read_csv('symbols_drop.csv')
symbols_drop = df_drop['symbol'].values

In [107]:
names_keep = []
symbols_keep = []
for i in range(len(symbols)):
    if not symbols[i] in symbols_drop:
        names_keep.append(names[i])
        symbols_keep.append(symbols[i])

In [113]:
df_keep = pd.DataFrame(names_keep)
df_keep.columns = ['company_name']
df_keep['symbol'] = symbols_keep

# df_keep = df_keep.groupby('symbol')['company_name'].apply(list)
# df_keep = df_keep.to_frame()
df_keep.head()

              company_name symbol
0  1-800-FLOWERS.COM, INC.   FLWS
1      21Vianet Group,Inc.   VNET
2   3D Systems Corporation    DDD
3                       3M    MMM
4                    51job   JOBS

In [114]:
df_keep.to_csv('symbols_keep.csv',index=False)